mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='polls/index.html'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
print(settings.STATIC_ROOT)

mysite/polls/urls.py
from django.urls import path
from rest_framework.settings import api_settings
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:good_id>/', views.detail, name='detail'),

    path('search/', views.search, name='search'),
    path('catalog/', views.catalog, name='catalog'),

    path('cartView/', views.cartView, name='cartView'),
    path('userCabinet/', views.userCabinet, name='userCabinet'),

    path('cart/<int:good_id>', views.addToCart, name='addToCart'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Good(models.Model):
    good_name = models.CharField(max_length=30)
    good_description = models.CharField(max_length=300)
    good_image = models.URLField()
    good_price = models.FloatField()

    def __str__(self):
        return self.good_name


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    good = models.ForeignKey(Good, on_delete=models.SET_NULL, null=True, blank=True)
    order_date = models.DateTimeField()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_image = models.URLField()
    user_cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from datetime import datetime
from .models import Good, Cart
from django.db.models import Q # new
from django.contrib.auth.decorators import login_required

def index(request):
    context = {'latest_question_list': 1}
    return render(request, 'polls/index.html', context)

def catalog(request):
    # if type.equals('all'):
    objects = Good.objects.all()
    print(objects)
    # else:
    #     objects = Question.objects.filter(Q(question_text__icontains=type))

    context = {'goods_list': objects}
    return render(request, 'polls/catalog.html', context)


def detail(request, good_id):
    good = get_object_or_404(Good, pk=good_id)
    return render(request, 'polls/detail.html', {'good': good})

@login_required
def cartView(request, user_id=1):
    try:
        # goodsAtCart = Good.objects.all()
        print("WASS",request.user)
        goodsInCart = Cart.objects.filter(user=request.user)
        goods_id = []
        for g in goodsInCart:
            goods_id.append(g.good_id)
        print(goods_id)
        # goodsAtCart = Good.objects.all()
        goodsAtCart = []
        for gid in goods_id:
            goodsAtCart.append(Good.objects.get(pk=gid))
        print(goodsAtCart)

        user = 1
        # goodsAtCart = Cart.objects.filter(Q(user_id__icontains=user))
    except EnvironmentError:
        # Redisplay the question voting form.
        return render(request, 'polls/cartView.html', {
            'cart': 1,
            'error_message': "You didn't select a choice.",
        })
    else:
        return render(request, 'polls/cartView.html', {'goodsAtCart': goodsAtCart})

@login_required
def userCabinet(request, user_id=1):
    try:
        # goodsAtCart = Good.objects.all()
        print("WASS",request.user)
        goodsInCart = Cart.objects.filter(user=request.user)
        goods_id = []
        for g in goodsInCart:
            goods_id.append(g.good_id)
        print(goods_id)
        # goodsAtCart = Good.objects.all()
        goodsAtCart = []
        for gid in goods_id:
            goodsAtCart.append(Good.objects.get(pk=gid))
        print(goodsAtCart)

        user = 1
        # goodsAtCart = Cart.objects.filter(Q(user_id__icontains=user))
    except EnvironmentError:
        # Redisplay the question voting form.
        return render(request, 'polls/userCabinet.html', {
            'cart': 1,
            'error_message': "You didn't select a choice.",
        })
    else:
        return render(request, 'polls/userCabinet.html', {'goodsAtCart': goodsInCart, 'user': request.user})


def addToCart(request, good_id):
    good = Good.objects.get(id=good_id)
    cart = Cart(user=request.user, good=good, order_date=datetime.now())
    cart.save()
    response = "Good added"
    return HttpResponseRedirect(reverse('polls:detail', args=(good_id,)))


def search(request):
    # question = get_object_or_404(Question, pk=question_id)
    try:
        # print(Question.objects.get(question_text=request.GET['searched_text']))
        query = request.GET.get('searched_text')
        selectedQuestions = Good.objects.filter(Q(good_name__icontains=query) | Q(good_description__icontains=query))
        for obj in selectedQuestions:
            print(obj)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': selectedQuestions,
            'error_message': "You didn't select a choice.",
        })
    else:
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return render(request, 'polls/searchResults.html', {'results': selectedQuestions})

mysite/polls/templates/polls/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
  <script>
function myFunction() {
  var txt;
  if (confirm("Do you want to delete!")) {
   //go to your delete path
  } else {
  //don't do anything
  }

}
</script>
    <script src="https://kit.fontawesome.com/ed7f7956b5.js"></script>
    <link rel="stylesheet" href="style.css">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  {% block head %}
  {% endblock %}
</head>
<body style="margin: 0px">
  <main>
<header style="  padding-bottom:15%; z-index:0;">
      <header style="position: fixed;  z-index: 9999; width: 100%; margin: 0;  top: 0;   opacity: 1; background-color: white;" >
<div style="display: flex; background-color: #86E6FB; align-items: center; font-size: 1vw;">
    <a style="padding-left: 5%; text-decoration: none;" href="{% url 'polls:index' %}">
        <h1>LogoImage</h1>
    </a>
    <a style="padding-left: 12%; text-decoration: none;" href="{% url 'polls:index' %}">
        <h2>Главная</h2>
    </a>
    <a style="padding-left: 12%; text-decoration: none;" href="{% url 'polls:catalog' %}">
        <h2>Каталог</h2>
    </a>
        <a style="padding-left: 12%; text-decoration: none;" href="#">
        <h2>Информация</h2>
    </a>
    <a style="padding-left: 12%; text-decoration: none;" href="#">
        <h2>Новости</h2>
    </a>
</div>
<div style="display: flex; align-items: center; margin: 10px; margin-bottom: 0; padding-left: 2%; font-size: 1vw;">
<form style="display: flex; width: 100%" action="{% url 'polls:search' %}" method="GET">
    <input type="text" style="width: 80%; height: 5vh; " name="searched_text">
<!--<input style="background-color: lightGreen" type="submit" value="Vote">-->
</form>
    <a href="{% url 'polls:cartView' %}" style="text-decoration: none;">
        <div style="padding-right: 5%; display: flex; align-items: center;">
            <i class="fas fa-cart-arrow-down fa-3x"></i>
            <h2 style="padding: 5%">Ваша корзина</h2>
        </div>
    </a>
  {%if user.is_authenticated %}
    <div style="padding-right: 5%; padding-left: 5%;">
      <a href="{% url 'polls:userCabinet' %}" style="text-decoration: none;">
        <h2>Личный кабинет, {{ user.get_username }} </h2>
      </a>
    </div>
  {% else %}
     <a href="{% url 'login'%}?next={{request.path}}"  style="text-decoration: none"><h2>Войти</h2></a>
   {% endif %}
</div>
          </header>
    </header>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

mysite/polls/templates/polls/cartView.html
{% extends 'polls/base.html' %}
{% block title %}Cart{% endblock %}

{% block content %}
<div>
    <article id="content" style="width: 80%; padding-left: 10%; padding-right: 10%;">
{% if goodsAtCart %}
    <ul style=" border-bottom: 2px solid #ccc;">
    {% for good in goodsAtCart %}
        <li style="display: flex; justify-content: space-between; padding-right: 5%; align-items: center">
            <div style="display: flex; justify-content: flex-start;  width: 100%">
                <img src="{{good.good_image}}" alt="Simply Easy Learning" width="200" height="200">
                <div style="padding-left: 5%; width: 100%">
                    <a href="{% url 'polls:detail' good.id %}"><h3>{{ good.good_name }}</h3></a>
                    <h4>{{good.good_description}}</h4>
                </div>
            </div>
            <h2>{{good.good_price}}</h2>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
        <div style="background-color: lightGreen; float: right; width: 10vw; height: 5vh; text-align: center">
            <h3 style="font-size: 1vw">Оформить заказ</h3>
</div>
    </article>

</div>
{% endblock %}

mysite/polls/templates/polls/catalog.html
{% extends 'polls/base.html' %}
{% block title %}Catalog{% endblock %}

{% block content %}
<div>
    <aside id="sidebar" style="width: 20%; float: left; padding-left: 5%;">
        <h3>Фильтр:</h3>
<form style="display: flex; width: 100%; " action="{% url 'polls:search' %}" method="GET">
    <input type="text" style="width: 80%; height: 5vh; " name="searched_text">
<!--<input style="background-color: lightGreen" type="submit" value="Vote">-->
</form>
    </aside>

    <article id="content" style="width: 75%; float: right;">
{% if goods_list %}
    <ul>
    {% for good in goods_list %}
        <li style="display: flex; justify-content: space-between; padding-right: 5%; align-items: center">
            <div style="display: flex; justify-content: flex-start;  width: 100%">
                <img src="{{good.good_image}}" alt="Simply Easy Learning" width="200" height="200">
                <div style="padding-left: 5%; width: 100%">
                    <a href="{% url 'polls:detail' good.id %}"><h3>{{ good.good_name }}</h3></a>
                    <h4>{{good.good_description}}</h4>
                </div>
            </div>
            <h2>{{good.good_price}}</h2>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </article>
</div>
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block title %}Detail{% endblock %}

{% block content %}
    {% if good %}
    <aside style="width: 20%; float: left; padding-left: 5%;">
        <div>
            <img src="{{good.good_image}}" alt="Simply Easy Learning" width="50%" height="50%">
        </div>
    </aside>
    <article id="content" style="width: 65%; float: right; text-align: left; padding-right: 10%;">

        <h1 style="height: 5vh;">{{ good.good_name }}</h1>
        <h3 style="height: 55vh;">{{good.good_description}}</h3>
        <div>
    <!--    <h2 style="height: 20vh;">Цена: {{good.good_price}}</h2>-->
            {%if user.is_authenticated %}
            <form action="{% url 'polls:addToCart' good.id %}" method="post">
                {% csrf_token %}
                <input style="background-color: lightGreen; width: 100%; height: 5vh; text-align: center;" type="submit" value="Купить: {{good.good_price}}">
            </form>
            {% endif %}

            </div>
    </article>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block title %}Main{% endblock %}

{% block content %}

<div style="margin: 3%; text-align: center; font-size: 1vw;">
    <div style="display: flex; padding-left: 10%; padding-right: 10%; width: 80%; item-align: center">
        <a href="{% url 'polls:catalog'%}" style="width: 33%; padding: 5%; background-color: #D03D3D">
            <div >
                <h1>Смартфоны</h1>
            </div>
        </a>
        <div style="width: 33%; padding: 5%;  background-color: #496ADF">
            <h1>Ноутбуки</h1>
        </div>
        <div style="width: 33%; padding: 5%; background-color: #5BC636"><h1>Телевизоры</h1></div>

    </div>
    <div style="display: flex; padding-left: 10%; padding-right: 10%; width: 80%; item-align: center">
        <div style="width: 33%; padding: 5%; background-color: #31D9D9">
            <h1>Блендеры</h1>
        </div>
        <div style="width: 33%; padding: 5%;  background-color: #B03964">
            <h1>Холодильники</h1>
        </div>
        <div style="width: 33%; padding: 5%; background-color: #F0F424"><h1>Стиральная машина</h1></div>
    </div>
    <div style="display: flex; padding-left: 10%; padding-right: 10%; width: 80%; item-align: center">
        <div style="width: 33%; padding: 5%; background-color: #C73CB0">
            <h1>Компьютеры</h1>
        </div>
        <div style="width: 33%; padding: 5%;  background-color: #EC984B">
            <h1>Фотоаппараты</h1>
        </div>
        <div style="width: 33%; padding: 5%; background-color: #806ABD"><h1>Дроны</h1></div>
    </div>
</div>
{% endblock %}

mysite/polls/templates/polls/searchResults.html
{% extends 'polls/base.html' %}
{% block title %}Search{% endblock %}

{% block content %}
{% if results %}
    <ul>
    {% for good in results %}
        <li style="display: flex; justify-content: space-between; padding-right: 5%; align-items: center">
            <div style="display: flex; justify-content: flex-start;  width: 100%">
                <img src="{{good.good_image}}" alt="Simply Easy Learning" width="200" height="200">
                <div style="padding-left: 5%; width: 100%">
                    <a href="{% url 'polls:detail' good.id %}"><h3>{{ good.good_name }}</h3></a>
                    <h4>{{good.good_description}}</h4>
                </div>
            </div>
            <h2>{{good.good_price}}</h2>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

mysite/polls/templates/polls/userCabinet.html
{% extends 'polls/base.html' %}
{% block title %}Cabinet{% endblock %}

{% block content %}
{% if user %}
<div>
        <aside id="sidebar" style="width: 20%; float: left;">
        <div style="margin: 5%;">
            <img src="{{user.profile.user_image}}"  width="100%" height="100%">
            <a href="{% url 'logout' %}">Выйти</a>
        </div>
    </aside>
    <article id="content" style="width: 65%; padding-right: 10%; float: right">
{% else %}
    <p>Strange.</p>
{% endif %}

{% if goodsAtCart %}
         <div style="border-left: 2px solid #ccc; padding-left: 3%">
        <div><h2>Ваши заказы:</h2></div>
    <ul>
    {% for cart in goodsAtCart %}
        <li style="display: flex; justify-content: space-between; padding-right: 5%; align-items: center">
            <div style="display: flex; justify-content: flex-start;  width: 100%">
                <img src="{{cart.good.good_image}}" alt="Simply Easy Learning" width="200" height="200">
                <div style="padding-left: 5%; width: 100%">
                    <a href="{% url 'polls:detail' cart.good.id %}"><h3>{{ cart.good.good_name }}</h3></a>
                    <h4>{{cart.good.good_description}}</h4>
                </div>
            </div>
            <div>
            <h2>{{cart.good.good_price}}</h2>
            <h2>{{cart.order_date}}</h2>
                </div>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </article>
</div>
</div>
{% endblock %}

mysite/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  {% block head %}
  {% endblock %}
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

mysite/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <a href="{% url 'logout' %}">logout</a>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}